name: "jira-version-action"

description: "Action to set the version in a set of issues"

branding:
  icon: git-pull-request
  color: green

inputs:
  project:
    required: true
    description: "Alias of Project"
  action:
    required: true
    description: "Action id"
  version:
    required: true
    description: "Version of release"
  issues:
    required: false
    description: "Set of issues"
  new-name:
    required: false
    description: "New name for version"
  branch-name:
    required: false
    description: "Name of branch"

runs:
  using: "node16"
  main: "./dist/index.js"
